### ISSUE TITLE
Potential data corruption/deletion bug while creating new difficulty

### ISSUE THREAD

**Issue by UnforeseenOcean** [PKBeam/Edda#46] opened 2023-06-15 07:09 UTC
Condition (as far as I can understand):
- Map is opened rather than created new
- A new difficulty was added after modifying the map
- The difficulty was changed after a new difficulty is created
- The map is then saved

Result:
- Previously written map, usually `Easy.dat`, is erased and replaced with a dummy file and requires recovery from autosave
- `info.dat` refers to old version without the new map, causing the editor to not see the map file of that difficulty

Attempted solutions:
- Re-installing the software (no change)
- Quitting and re-entering map (no change)
- Replace the map with the backup while the software is open (causes the data to be reverted back to the dummy data once the program is closed)

**Comment by Brollyy** [comment] 2023-07-12 15:48
I was finally able to reproduce this issue on my end - will look into what's causing it.

**Comment by Brollyy** [comment] 2023-07-14 20:27
This is caused by references to some resources not being properly disposed when closing the main window, which causes the autosave to keep running and overwriting the map files with garbage on the starting window.

It looks to me like #16 had the same cause - I'm closing it as duplicate.

**Closed** 2023-07-17 00:35 UTC
Labels: bug
